[package]
name = "rust-rltk-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# NOTE: `rltk` switched to `bracket-lib` and should be identical
bracket-lib = "~0.8"
